global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cloud-lab-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000
        labels:
          service: cloud-lab
          environment: local

  - job_name: cloud-lab-vm-node-exporter
    metrics_path: /metrics
    http_sd_configs:
      - url: http://backend:8000/metrics/vm-targets
        refresh_interval: 30s
