[student_vms]
# Les IPs des VMs seront ajoutées ici automatiquement
# Exemple : 10.10.1.20 ansible_user=student ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
